from .loss import (
    Loss,
    MSELoss,
    MAELoss,
    HingeLoss,
    BinaryCrossEntropyLoss,
    CategoricalCrossEntropyLoss,
    mse_loss,
    mae_loss,
    hinge_loss,
    binary_crossentropy_loss,
    categorical_crossentropy_loss,
    LOSS_REGISTRY,
    register_loss,
    get_loss,
)
